### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by bettercallazamat** [abouhid/Pokelex#1]
Consider these suggestions:
1) When the index page is loaded, when data is not fetched yet, it shows "No pokemon found", but it's better to inform that data is loading.
2) Add conditions for styling in cases when there is a pokemon with more or less than 3 steps in evolution.

Good job so far!!!

**Comment by Zubenna** [comment]
Nice job. The project looks good.
You may consider the following:
- You can still improve the responsiveness to avoid breaking at some points.
- Remember to write your test.
Happy coding.
